name: other-blank1
on:
  workflow_call:
    inputs:
      environment:
        description: "blank1 environment"
        type: string
    secrets:
      GSU:
        description: "user"
        required: true
      GSP:
        description: "user"
        required: true
      RS:
        description: "user"
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      usr: ${{ secrets.GSU }}
      pass: ${{ secrets.GSP }}
      repo-secret: ${{ secrets.RS }}
    environment: ${{ inputs.environment }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          if [ -n '${{ env.usr }}' ] && [ -n '${{ env.pass }}' ]
          then
            echo "using user: ${{ env.usr }}"
            ${{ env.usr }}
            echo "using pass: ${{ env.pass }}"
            ${{ env.pass }}
          else
            echo "user nor pass not provided"
          fi
          
          command="ls ../"
          $command
          echo "command: '$command'"
          echo "'$pass'"
          echo "'$user'"
          echo "'${{ env.repo-secret }}'"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
