# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment-type:
        description: "Environment"
        type: choice
        options:
          - Test
          - Stage

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      usr: ${{ secrets.T_U }}
      pass: ${{ secrets.T_P }}
    environment: ${{ inputs.environment-type }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          if [ -n '${{ env.usr }}' ]
          then
            echo "using user ${{ env.usr }}"
            command="${{ env.usr }};"
          else
            echo "user not provided"
          fi
          
          if [ -n '${{ env.usr }}' ]
          then
            echo "using pass ${{ env.pass }}"
            command=$command${{ env.pass }}
          else
            echo "pass not provided"
          fi
          
          echo "$command"
          $command
          echo $pass

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
